import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('log and edit food offline; recipes, backups and mobile layout', async ({ page, context }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/'); await expect(page.getByRole('heading', { name: 'Your day, at a glance.' })).toBeVisible();
  await page.getByRole('button', { name: 'Log food', exact: true }).click();
  await page.getByRole('textbox', { name: 'Search foods or recipes' }).fill('Chicken breast, skinless');
  await page.getByRole('button', { name: /Chicken breast, skinless.*Raw/ }).click();
  await page.getByLabel('Amount eaten (g)').fill('200');
  await expect(page.locator('.nutrition-preview strong')).toHaveText('240');
  await page.getByRole('button', { name: 'Add to diary', exact: true }).click();
  await expect(page.locator('.hero-number')).toHaveText('240 kcal');
  await page.getByRole('button', { name: 'Skip breakfast for this day', exact: true }).click();
  await expect(page.getByText('Skipped for this day', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Undo skip breakfast', exact: true }).click();
  await expect(page.getByText('Skipped for this day', { exact: true })).not.toBeVisible();

  await page.evaluate(async () => { await navigator.serviceWorker.ready; });
  await page.reload(); await page.waitForFunction(() => !!navigator.serviceWorker.controller);
  await context.setOffline(true); await page.reload();
  await expect(page.locator('.hero-number')).toHaveText('240 kcal');
  await page.getByRole('button', { name: 'Edit Chicken breast, skinless', exact: true }).click();
  await page.getByLabel('Amount eaten (g)').fill('250'); await page.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(page.locator('.hero-number')).toHaveText('300 kcal');
  await page.getByRole('button', { name: 'Recipes', exact: true }).first().click();
  await page.getByRole('button', { name: 'New recipe', exact: true }).click();
  await page.getByLabel('Recipe name').fill('Chicken batch');
  await page.getByLabel('Ingredient', { exact: true }).selectOption({ label: 'Chicken breast, skinless · Raw' });
  await page.getByLabel('Grams', { exact: true }).fill('1000'); await page.getByRole('button', { name: 'Add ingredient', exact: true }).click();
  await page.getByLabel('Finished dish weight (g)').fill('800'); await page.getByLabel('Number of servings').fill('4');
  await page.getByRole('button', { name: 'Create recipe', exact: true }).click();
  await expect(page.locator('.recipe-kcal')).toHaveText('300 kcal / serving');
  await page.getByRole('button', { name: 'Log a portion', exact: true }).click();
  await page.getByLabel('Measure', { exact: true }).selectOption('servings');
  await page.getByLabel('Servings eaten').fill('1.5');
  await expect(page.locator('.nutrition-preview strong')).toHaveText('450');
  await page.getByRole('button', { name: 'Add to diary', exact: true }).click();
  await page.getByRole('button', { name: 'Overview', exact: true }).click();
  await expect(page.locator('.hero-number')).toHaveText('750 kcal');
  await page.getByRole('button', { name: 'Log weight', exact: true }).click();
  await page.getByLabel('Weight (kg)', { exact: true }).fill('110');
  await page.getByRole('button', { name: 'Save weigh-in' }).click();
  await page.getByRole('button', { name: 'Settings & sync', exact: true }).click();
  await page.getByLabel('First name').fill('Neil'); await page.getByLabel('Age', { exact: true }).fill('33');
  await page.getByLabel('Height (cm)').fill('180'); await page.getByLabel('Starting weight (kg)').fill('110');
  await page.getByRole('button', { name: 'Save profile', exact: true }).click();
  const downloadPromise = page.waitForEvent('download'); await page.getByRole('button', { name: 'Export backup', exact: true }).click();
  const file = await downloadPromise; const raw = await readFile((await file.path())!, 'utf8');
  expect(JSON.parse(raw).entries).toHaveLength(2); expect(JSON.parse(raw).profile.name).toBe('Neil'); expect(JSON.parse(raw).skippedMeals).toEqual([]);
  await context.setOffline(false);
  await page.getByRole('button', { name: 'Overview', exact: true }).click();
  await page.screenshot({ path: 'test-results/dashboard-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator('.mobile-nav')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/dashboard-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Foods', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Food library', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});

test('local sync authenticates, merges two devices and rejects stale writes', async ({ browser, request }, testInfo) => {
  const key = (await readFile(`${testInfo.config.metadata.dataDir}/pairing-key`, 'utf8')).trim();
  const denied = await request.get('/api/diary'); expect(denied.status()).toBe(401);
  const contextA = await browser.newContext(), contextB = await browser.newContext();
  const a = await contextA.newPage(), b = await contextB.newPage();
  async function connect(page: typeof a) {
    await page.goto('http://localhost:4175'); await page.getByRole('button', { name: 'Settings & sync', exact: true }).click();
    await page.getByRole('button', { name: 'Local sync', exact: true }).click();
    await page.getByLabel('Local server URL').fill('http://localhost:4175'); await page.getByLabel('Pairing key').fill(key);
    await page.getByRole('button', { name: 'Connect local server', exact: true }).click();
    await expect(page.getByText('Local server connected. Sync is ready.')).toBeVisible();
    await page.getByRole('button', { name: 'Sync now', exact: true }).click();
    await expect(page.locator('.sync-controls p')).toContainText('Last synced');
  }
  await connect(a); await connect(b);
  await a.getByLabel('First name').fill('Shared diary'); await a.getByRole('button', { name: 'Save profile', exact: true }).click();
  // No Sync button: edits upload automatically and the other device refreshes on return.
  await expect.poll(async () => (await (await request.get('/api/diary', { headers: { Authorization: `Bearer ${key}` } })).json()).payload.profile.name).toBe('Shared diary');
  await b.evaluate(() => document.dispatchEvent(new Event('visibilitychange')));
  await expect(b.locator('.sidebar-profile strong')).toHaveText('Shared diary');
  await expect(b.getByLabel('First name')).toHaveValue('Shared diary');
  await a.getByRole('button', { name: 'Overview', exact: true }).click();
  await a.getByRole('button', { name: 'Skip breakfast for this day', exact: true }).click();
  await contextA.setOffline(true);
  await a.getByRole('button', { name: 'Recipes', exact: true }).first().click();
  await a.getByRole('button', { name: 'New recipe', exact: true }).click();
  await a.getByLabel('Recipe name').fill('Offline lunch batch');
  await a.getByLabel('Ingredient', { exact: true }).selectOption({ label: 'Chicken breast, skinless · Raw' });
  await a.getByLabel('Grams', { exact: true }).fill('1000');
  await a.getByRole('button', { name: 'Add ingredient', exact: true }).click();
  await a.getByLabel('Finished dish weight (g)').fill('800');
  await a.getByLabel('Number of servings').fill('4');
  await a.getByRole('button', { name: 'Create recipe', exact: true }).click();
  await contextA.setOffline(false);
  await expect.poll(async () => (await (await request.get('/api/diary', { headers: { Authorization: `Bearer ${key}` } })).json()).payload.recipes.length).toBe(1);
  await b.evaluate(() => document.dispatchEvent(new Event('visibilitychange')));
  await b.getByRole('button', { name: 'Recipes', exact: true }).first().click();
  await expect(b.getByRole('heading', { name: 'Offline lunch batch', exact: true })).toBeVisible();
  await b.getByRole('button', { name: 'Overview', exact: true }).click();
  await expect(b.getByText('Skipped for this day', { exact: true })).toBeVisible();
  const invalid = await request.post('/api/diary', { headers: { Authorization: `Bearer ${key}` }, data: { expectedRevision: 1, payload: { version: 1, entries: [] } } });
  expect(invalid.status()).toBe(400);
  const latest = await request.get('/api/diary', { headers: { Authorization: `Bearer ${key}` } });
  const snapshot = await latest.json();
  const stale = await request.post('/api/diary', { headers: { Authorization: `Bearer ${key}` }, data: { expectedRevision: 0, payload: snapshot.payload } });
  expect(stale.status()).toBe(409);
  expect((await (await request.get('/api/diary', { headers: { Authorization: `Bearer ${key}` } })).json()).payload.profile.name).toBe('Shared diary');
  await contextA.close(); await contextB.close();
});
