import { expect, test } from '@playwright/test';

test('review a sourced food, save a weighed serving, log its time and use it offline', async ({ page, context }) => {
  await page.goto('/#foods');
  await page.getByRole('button', { name: 'Import food', exact: true }).click();
  await page.getByLabel('Search food sources').fill('carrot cake slice');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.locator('.import-result').filter({ hasText: 'Cake or cupcake, carrot' }).click();
  await expect(page.locator('.import-source')).toContainText('USDA FNDDS 2021–2023');
  await expect(page.locator('.import-source a')).toHaveAttribute('href', /fdc\.nal\.usda\.gov\/food-details\/\d+\/nutrients/);
  await expect(page.locator('.import-nutrition')).toContainText('374 kcal');
  await page.getByLabel('Reference portion').selectOption({ label: '1 piece/slice, any size (200 g)' });
  await expect(page.locator('.import-nutrition')).toContainText('748 kcal');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ colorScheme: 'dark' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/food-import-preview-mobile.png' });
  await page.setViewportSize({ width: 1440, height: 1080 });
  await page.getByRole('button', { name: 'Review & add', exact: true }).click();
  await page.getByLabel('Food name', { exact: true }).fill('My carrot cake slice');
  await page.getByLabel('Serving name', { exact: true }).fill('1 slice');
  await page.getByLabel('Serving weight (g)').fill('80');
  await page.getByLabel('I’ve checked the food, source and nutrition.').check();
  await page.getByRole('button', { name: 'Add to library', exact: true }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByLabel('Search food library').fill('My carrot');
  await expect(page.locator('.food-row')).toHaveCount(1);
  await expect(page.locator('.food-row a')).toHaveAttribute('href', /fdc\.nal\.usda\.gov/);
  await page.getByRole('button', { name: 'Log My carrot cake slice Ready to eat' }).click();
  await expect(page.getByLabel('Amount eaten (g)')).toHaveValue('80');
  await page.getByLabel('Meal', { exact: true }).selectOption('Snacks');
  await page.getByLabel('Time eaten').fill('10:35');
  await expect(page.locator('.nutrition-preview strong')).toHaveText('299');
  await page.getByRole('button', { name: 'Add to diary', exact: true }).click();
  await page.getByRole('button', { name: 'Food diary', exact: true }).click();
  await expect(page.locator('.diary-entry')).toContainText('10:35');
  await page.getByRole('button', { name: 'Edit My carrot cake slice' }).click();
  await expect(page.getByLabel('Time eaten')).toHaveValue('10:35');
  await page.getByRole('button', { name: 'Close dialog' }).click();
  await page.evaluate(async () => { await navigator.serviceWorker.ready; });
  await page.reload(); await page.waitForFunction(() => !!navigator.serviceWorker.controller);
  await context.setOffline(true); await page.reload();
  await expect(page.locator('.diary-entry')).toContainText('10:35');
  await page.getByRole('button', { name: 'Food library', exact: true }).click();
  await page.getByRole('button', { name: 'Import food', exact: true }).click();
  await page.getByLabel('Search food sources').fill('carrot cake slice');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.locator('.import-result').filter({ hasText: 'Cake or cupcake, carrot' }).click();
  await expect(page.getByText('Already in your library', { exact: false })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Review & add', exact: true })).toBeDisabled();
});

test('packaged lookup requires source review and missing nutrient values before import', async ({ page }) => {
  let requests = 0;
  await page.route('**/api/food-search?*', async route => {
    requests++; const url = new URL(route.request().url());
    if (url.searchParams.has('q')) return route.fulfill({ json: { hits: [{ code: '3017620422003', product_name: 'Test tuna', brands: ['Test Brand'], quantity: '160 g' }], page_count: 1 } });
    return route.fulfill({ json: { product: { code: '3017620422003', product_name: 'Test tuna', brands: 'Test Brand', serving_size: '1 tin (120 g)', nutrition: { aggregated_set: { per: '100g', preparation: 'as_sold', nutrients: { 'energy-kcal': { unit: 'kcal', value: 150 }, proteins: { unit: 'g', value: 25 }, carbohydrates: { unit: 'g', value: 0 }, fat: { unit: 'g', value: 5 } } } } } } });
  });
  await page.goto('/#foods');
  await page.getByRole('button', { name: 'Import food', exact: true }).click();
  await page.getByRole('button', { name: 'Packaged products', exact: true }).click();
  await page.getByLabel('Search food sources').fill('Test tuna');
  expect(requests).toBe(0);
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.locator('.import-result').click();
  await expect(page.locator('.import-source')).toContainText('Test Brand');
  await expect(page.locator('.import-source')).toContainText('3017620422003');
  await expect(page.locator('.import-nutrition')).toContainText('Missing');
  await page.getByRole('button', { name: 'Review & add', exact: true }).click();
  await expect(page.getByLabel('Fibre (g)')).toHaveValue('');
  await page.getByLabel('I’ve checked the food, source and nutrition.').check();
  await page.getByRole('button', { name: 'Add to library', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.getByLabel('Fibre (g)').fill('0');
  await page.getByRole('button', { name: 'Add to library', exact: true }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByLabel('Search food library').fill('Test tuna');
  await expect(page.locator('.food-row')).toHaveCount(1);
  await expect(page.locator('.food-row a')).toHaveAttribute('href', 'https://world.openfoodfacts.org/product/3017620422003');
  await page.getByRole('button', { name: 'Edit Test tuna', exact: true }).click();
  await expect(page.locator('.import-source')).toContainText('Open Food Facts');
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  expect(requests).toBe(2);
});

test('paste ingredients, review sources and amounts, then save a recipe', async ({ page }) => {
  await page.goto('/#recipes');
  await page.getByRole('button', { name: 'New recipe', exact: true }).click();
  await page.getByLabel('Recipe name').fill('Work lunch estimate');
  await page.getByText('Paste several ingredients', { exact: true }).click();
  await page.getByLabel('Ingredient list').fill('Olive oil 10 g\nTomato paste 20 g\nCapers');
  await page.getByRole('button', { name: 'Find ingredients', exact: true }).click();
  await expect(page.locator('.quick-row')).toHaveCount(3);
  await expect(page.getByLabel('Grams of Capers')).toHaveValue('');
  await expect(page.getByRole('button', { name: 'Add reviewed ingredients' })).toBeDisabled();
  await page.getByLabel('Grams of Capers').fill('10');
  await expect(page.locator('.quick-nutrition a')).toHaveCount(3);
  await page.getByRole('button', { name: 'Add reviewed ingredients' }).click();
  await expect(page.locator('.ingredient')).toHaveCount(3);
  await page.getByLabel('Finished dish weight (g)').fill('40');
  await page.getByLabel('Estimated recipe or portions').check();
  await page.getByRole('button', { name: 'Create recipe', exact: true }).click();
  await expect(page.locator('.recipe-card')).toContainText('Work lunch estimate');
  await expect(page.locator('.recipe-card')).toContainText('Estimate');
  await page.getByRole('button', { name: 'Food library', exact: true }).click();
  await page.getByLabel('Search food library').fill('capers');
  await expect(page.locator('.food-row')).toHaveCount(1);
});
