import { expect, test } from '@playwright/test';

test('a thousand foods stay searchable, paged and usable offline on mobile', async ({ page, context }) => {
  await page.goto('/');
  await expect(page.locator('.hero-number')).toBeVisible();
  // Only this isolated test browser's diary is populated.
  await page.evaluate(async () => new Promise<void>((resolve, reject) => {
    const request = indexedDB.open('steady-fitness', 1);
    request.onerror = () => reject(request.error);
    request.onsuccess = () => {
      const database = request.result, tx = database.transaction('app', 'readwrite'), store = tx.objectStore('app');
      const read = store.get('state');
      read.onsuccess = () => {
        const state = read.result, food = state.foods[0];
        state.foods = Array.from({ length: 1000 }, (_, i) => ({ ...food, id: `test-${i}`, name: `Food ${String(i).padStart(4, '0')}`, custom: true, group: i % 2 ? 'Grains' : 'Protein' }));
        state.recipes = Array.from({ length: 25 }, (_, i) => ({ id: `recipe-${i}`, name: `Batch ${String(i).padStart(2, '0')}`, ingredients: [{ food, grams: 100 }], servings: 1, yieldGrams: 100 }));
        store.put(state, 'state');
      };
      tx.oncomplete = () => { database.close(); resolve(); };
      tx.onerror = () => reject(tx.error);
    };
  }));
  await page.reload();
  await page.getByRole('button', { name: 'Food library', exact: true }).click();
  const pages = page.getByRole('navigation', { name: 'Food library pages', exact: true });
  await expect(page.locator('.food-row')).toHaveCount(20);
  await expect(pages).toContainText('1–20 of 1,000');
  await expect(pages.getByRole('button', { name: 'Previous page' })).toBeDisabled();
  await pages.getByLabel('Page', { exact: true }).selectOption('50');
  await expect(page.locator('.food-row').last()).toContainText('Food 0999');
  await expect(pages.getByRole('button', { name: 'Next page' })).toBeDisabled();
  await page.getByLabel('Food category').selectOption('Protein');
  await expect(pages).toContainText('1–20 of 500');
  await pages.getByLabel('Items per page').selectOption('10');
  await expect(page.locator('.food-row')).toHaveCount(10);
  await page.getByLabel('Food category').selectOption('All foods');
  await page.getByLabel('Search food library').fill(' 0999   raw ');
  await expect(page.locator('.food-row')).toHaveCount(1);
  await page.getByRole('button', { name: 'Log Food 0999 Raw' }).click();
  await page.getByLabel('Amount eaten (g)').fill('50');
  await expect(page.locator('.nutrition-preview strong')).toHaveText('60');
  await page.getByRole('button', { name: 'Add to diary', exact: true }).click();
  await page.evaluate(async () => { await navigator.serviceWorker.ready; });
  await page.reload();
  await page.waitForFunction(() => !!navigator.serviceWorker.controller);
  await context.setOffline(true);
  await page.reload();
  await expect(page).toHaveURL(/#foods$/);
  await page.getByLabel('Search food library').fill('not-a-food');
  await expect(page.getByRole('heading', { name: 'No foods found' })).toBeVisible();
  await page.getByLabel('Search food library').fill('0999');
  await expect(page.locator('.food-row')).toContainText('Food 0999');
  await page.getByLabel('Search food library').fill('');
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/foods-charcoal-mobile.png' });
  await page.setViewportSize({ width: 1440, height: 1080 });
  await page.screenshot({ path: 'test-results/foods-charcoal-desktop.png' });
  await page.emulateMedia({ colorScheme: 'light' });
  await page.screenshot({ path: 'test-results/foods-light-desktop.png' });

  await page.getByRole('button', { name: 'Log food', exact: true }).click();
  await expect(page.locator('.food-option')).toHaveCount(20);
  await page.getByLabel('Search foods or recipes').fill('0999');
  await expect(page.locator('.food-option')).toHaveCount(1);
  await page.locator('.food-option').click();
  await expect(page.locator('.selected-food')).toContainText('Food 0999');
  await page.getByRole('button', { name: 'Close dialog' }).click();
  await page.getByRole('button', { name: 'Recipes', exact: true }).first().click();
  await expect(page.locator('.recipe-card')).toHaveCount(12);
  await page.getByLabel('Search recipes').fill('24');
  await expect(page.locator('.recipe-card')).toHaveCount(1);
  await expect(page.locator('.recipe-card')).toContainText('Batch 24');
  await page.getByRole('button', { name: 'New recipe', exact: true }).click();
  await expect(page.getByLabel('Ingredient', { exact: true }).locator('option')).toHaveCount(30);
  await page.getByLabel('Search ingredients').fill('0999');
  await page.getByLabel('Ingredient', { exact: true }).selectOption({ label: 'Food 0999 · Raw' });
  await page.getByRole('button', { name: 'Add ingredient', exact: true }).click();
  await expect(page.locator('.ingredient')).toContainText('Food 0999');
  await page.getByLabel('Search ingredients').fill('no match');
  await expect(page.getByRole('button', { name: 'Add ingredient', exact: true })).toBeDisabled();
});

test('profile menu, refresh and back navigation work in a short window', async ({ page }) => {
  await page.setViewportSize({ width: 1100, height: 360 });
  await page.goto('/');
  await expect(page.locator('.hero-number')).toBeVisible();
  const sidebar = page.locator('.sidebar');
  expect(await sidebar.evaluate(node => node.scrollHeight > node.clientHeight)).toBe(true);
  await sidebar.hover();
  await page.mouse.wheel(0, 900);
  await expect.poll(() => sidebar.evaluate(node => node.scrollTop)).toBeGreaterThan(0);
  await page.getByRole('button', { name: 'Settings & sync', exact: true }).click();
  await expect(page).toHaveURL(/#settings$/);
  await page.getByRole('button', { name: 'Open profile menu' }).click();
  const menu = page.locator('.profile-menu');
  await expect(menu).toBeVisible();
  await expect(page.getByRole('button', { name: 'Open profile menu' })).toHaveAttribute('aria-expanded', 'true');
  await menu.getByRole('button', { name: 'Dark', exact: true }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  const box = (await menu.boundingBox())!;
  expect(box.y + box.height).toBeLessThanOrEqual(360);
  await page.keyboard.press('Escape');
  await expect(menu).not.toBeVisible();
  await page.getByRole('button', { name: 'Open profile menu' }).click();
  await menu.getByRole('button', { name: 'Profile & settings' }).click();
  await expect(menu).not.toBeVisible();
  await expect(page.getByRole('heading', { name: 'Settings', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Recipes', exact: true }).first().click();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Recipes', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Activity', exact: true }).first().click();
  await expect(page.getByRole('heading', { name: 'Activity', exact: true })).toBeVisible();
  await expect(page.getByText('Watch → Zepp', { exact: false })).not.toBeVisible();
  await page.getByText('Sync help', { exact: true }).click();
  await expect(page.getByText('Watch → Zepp', { exact: false })).toBeVisible();
  await page.goBack();
  await expect(page.getByRole('heading', { name: 'Recipes', exact: true })).toBeVisible();
  await page.goForward();
  await expect(page.getByRole('heading', { name: 'Activity', exact: true })).toBeVisible();
  await page.setViewportSize({ width: 1440, height: 1080 });
  await page.screenshot({ path: 'test-results/activity-charcoal-desktop.png' });
  await page.getByRole('button', { name: 'Open profile menu' }).click();
  await page.screenshot({ path: 'test-results/profile-menu-charcoal.png' });
  await page.getByRole('heading', { name: 'Activity', exact: true }).click();
  await expect(menu).not.toBeVisible();
});
