import { ArrowDownRight, ArrowUpRight, ChevronLeft, ChevronRight, Flame, Footprints, Plus, Scale, Sunrise, Sun, Moon, Cookie, Pencil, Trash2, Watch, CalendarDays, Utensils } from 'lucide-react';
import { dayActivity, dayTotals, dateLabel, daysEnding, entryMacros, fmt, localDate, meals, shiftDate, type Entry, type Meal, type State } from './model';
import { Empty, LinkButton, MacroStrip, SectionHeading } from './ui';

export type DiaryActions = { skip: (meal: Meal) => void; undoSkip: (meal: Meal) => void; add: (meal: Meal) => void; edit: (e: Entry) => void; remove: (e: Entry) => void; weight: () => void; activity: () => void; settings: () => void; progress: () => void };
export function DateSwitcher({ date, onChange }: { date: string; onChange: (d: string) => void }) {
  return <div className="date-switcher"><button className="icon-button" aria-label="Previous day" onClick={() => onChange(shiftDate(date, -1))}><ChevronLeft size={18} /></button><label><CalendarDays size={16} /><span>{date === localDate() ? 'Today' : dateLabel(date)}</span><input aria-label="Selected date" type="date" value={date} onChange={e => e.target.value && onChange(e.target.value)} /></label><button className="icon-button" aria-label="Next day" onClick={() => onChange(shiftDate(date, 1))}><ChevronRight size={18} /></button></div>;
}

export function WeekChart({ state, date, select }: { state: State; date: string; select?: (d: string) => void }) {
  const dates = daysEnding(date, 7), totals = dates.map(d => dayTotals(state, d).kcal);
  const max = Math.max(...totals, state.profile.calorieGoal ?? 0, 500);
  return <div className="week-chart" role="img" aria-label={`Daily calories: ${dates.map((d, i) => `${dateLabel(d)} ${fmt(totals[i])} kcal`).join(', ')}`}>
    <div className="chart-grid"><span>{fmt(max)}</span><span>{fmt(max / 2)}</span><span>0 kcal</span></div>
    <div className="chart-bars">{dates.map((d, i) => <button className={`chart-column ${d === date ? 'current' : ''}`} key={d} aria-label={`${dateLabel(d)}: ${fmt(totals[i])} kcal`} onClick={() => select?.(d)} title={`${dateLabel(d)} · ${fmt(totals[i])} kcal`}><div className="bar-track"><div className={`bar ${totals[i] ? '' : 'no-data'}`} style={{ height: `${Math.max(totals[i] / max * 100, 2)}%` }} /></div><span>{dateLabel(d, { weekday: 'short' })}</span></button>)}</div>
  </div>;
}

export function Diary({ state, date, actions }: { state: State; date: string; actions: DiaryActions }) {
  const icons = { Breakfast: Sunrise, Lunch: Sun, Dinner: Moon, Snacks: Cookie };
  return <section className="card diary-card"><SectionHeading title="Your food diary" aside={<span className="tag">{state.entries.filter(e => e.date === date).length} entries</span>} /><div className="meals">{meals.map(meal => {
    const entries = state.entries.filter(e => e.date === date && e.meal === meal), Icon = icons[meal];
    const skipped = state.skippedMeals.some(x => x.date === date && x.meal === meal);
    return <div className="meal" key={meal}><div className="meal-header"><span className={`meal-icon ${meal.toLowerCase()}`}><Icon size={18} /></span><h3>{meal}</h3><span>{fmt(entries.reduce((sum, e) => sum + entryMacros(e).kcal, 0))}<small> kcal</small></span><button className="icon-button" aria-label={`Add ${meal.toLowerCase()}`} onClick={() => actions.add(meal)}><Plus size={18} /></button></div>{skipped && !entries.length && <div className="meal-skip"><span>Skipped for this day</span><button className="text-button" onClick={() => actions.undoSkip(meal)} aria-label={`Undo skip ${meal.toLowerCase()}`}>Undo</button></div>}{entries.length ? entries.map(e => <div className="diary-entry" key={e.id}><div><strong>{e.name}</strong><small>{fmt(e.grams, 1)} g · {e.preparation}</small></div><b>{fmt(entryMacros(e).kcal)}<small> kcal</small></b><button className="icon-button" onClick={() => actions.edit(e)} aria-label={`Edit ${e.name}`}><Pencil size={15} /></button><button className="icon-button delete" onClick={() => actions.remove(e)} aria-label={`Delete ${e.name}`}><Trash2 size={15} /></button></div>) : <button className="add-meal" onClick={() => actions.add(meal)}>Add your {meal.toLowerCase()}<Plus size={14} /></button>}{!entries.length && !skipped && meal !== 'Snacks' && <button className="text-button meal-skip-button" onClick={() => actions.skip(meal)} aria-label={`Skip ${meal.toLowerCase()} for this day`}>Skip this meal today</button>}</div>;
  })}</div></section>;
}

export default function Dashboard({ state, date, setDate, actions }: { state: State; date: string; setDate: (d: string) => void; actions: DiaryActions }) {
  const totals = dayTotals(state, date), activity = dayActivity(state, date), target = state.profile.calorieGoal;
  const remaining = target === null ? null : target - totals.kcal;
  const progress = target ? Math.min(totals.kcal / target, 1) : 0;
  const weights = [...state.weights].filter(w => w.date <= date).sort((a, b) => a.date.localeCompare(b.date));
  const latest = weights.at(-1), previous = weights.at(-2);
  const week = daysEnding(date, 7), logged = week.filter(d => state.entries.some(e => e.date === d)).length;
  return <><div className="page-heading"><div><h1>{date === localDate() ? `Your day, ${state.profile.name || 'at a glance'}.` : `A look at ${dateLabel(date)}.`}</h1></div><DateSwitcher date={date} onChange={setDate} /></div>
    <div className="summary-grid"><section className="calorie-card"><div className="card-topline"><span><Flame size={18} />Daily nutrition</span><span className="light-tag">{date === localDate() ? 'Today' : dateLabel(date)}</span></div><div className="calorie-body"><div><div className="hero-number">{fmt(totals.kcal)}<span> kcal</span></div><p>{target ? `of ${fmt(target)} kcal daily target` : 'No calorie target set'}</p></div><div className="calorie-ring" style={{ background: `conic-gradient(#d6ed9f ${progress * 360}deg, #ffffff20 0deg)` }}><div><Utensils size={24} /><span>{target ? `${Math.round(progress * 100)}%` : 'Your day'}</span></div></div></div><div className="calorie-footer">{remaining === null ? <button onClick={actions.settings}>Set calorie target<ArrowUpRight size={16} /></button> : <><span>{fmt(Math.abs(remaining))} kcal {remaining >= 0 ? 'remaining' : 'above target'}</span><span>Food target only</span></>}</div></section>
      <section className="card macro-card"><div className="card-topline"><h2>Macros</h2><span className="tag">Nutrition</span></div><div className="macro-numbers">{(['protein', 'carbs', 'fat'] as const).map(k => <div key={k}><i className={`dot ${k}`} /><span>{k[0].toUpperCase() + k.slice(1)}</span><strong>{fmt(totals[k], 1)}<small> g</small></strong><div className={`macro-underline ${k}`} /></div>)}</div><div className="card-foot"><span>Fibre</span><b>{fmt(totals.fibre, 1)} g</b></div></section></div>
    <div className="dashboard-columns"><Diary state={state} date={date} actions={actions} /><div className="dashboard-right"><section className="card"><SectionHeading title="This week" aside={<LinkButton onClick={actions.progress}>Progress</LinkButton>} /><div className="chart-summary"><strong>{logged}<span> / 7 days</span></strong><small>with food logged</small></div><WeekChart state={state} date={date} select={setDate} /><p className="chart-caption">Calories logged · last 7 days</p></section>
      <section className="gentle-card compact-activity-link"><Watch size={22} strokeWidth={1.5} /><LinkButton onClick={actions.activity}>View activity</LinkButton></section></div></div>
    <div className="movement-grid"><section className="card movement-card"><div className="metric-icon"><Footprints size={21} /></div><div><p>Steps</p><strong>{activity?.steps != null ? fmt(activity.steps) : '—'}</strong><small>{activity ? activity.source === 'manual' ? 'Entered by you' : 'Imported' : 'No data yet'}</small></div><button className="icon-button" aria-label="Add daily activity" onClick={actions.activity}><ArrowUpRight size={19} /></button></section><section className="card movement-card"><div className="metric-icon peach"><Flame size={21} /></div><div><p>Active energy</p><strong>{activity?.activeKcal != null ? fmt(activity.activeKcal) : '—'}<span> kcal</span></strong><small>Estimated · separate from food target</small></div><button className="icon-button" aria-label="View daily activity" onClick={actions.activity}><ArrowUpRight size={19} /></button></section><section className="card movement-card"><div className="metric-icon lavender"><Scale size={21} /></div><div><p>Latest weigh-in</p><strong>{latest ? fmt(latest.kg, 1) : '—'}<span> kg</span></strong><small>{latest ? previous ? <><span className="inline-icon">{latest.kg <= previous.kg ? <ArrowDownRight size={12} /> : <ArrowUpRight size={12} />}</span>{fmt(Math.abs(latest.kg - previous.kg), 1)} kg since previous entry</> : dateLabel(latest.date) : 'No weigh-ins yet'}</small></div><button className="icon-button" aria-label="Log weight" onClick={actions.weight}><Plus size={19} /></button></section></div>
  </>;
}

export function Progress({ state, date, period, setPeriod, logWeight, deleteWeight }: { state: State; date: string; period: number; setPeriod: (n: number) => void; logWeight: () => void; deleteWeight: (date: string) => void }) {
  const dates = daysEnding(date, period), logged = dates.filter(d => state.entries.some(e => e.date === d));
  const totalKcal = dates.reduce((n, d) => n + dayTotals(state, d).kcal, 0);
  const active = dates.map(d => dayActivity(state, d)).filter(a => a?.steps != null);
  const weights = [...state.weights].filter(w => dates.includes(w.date)).sort((a, b) => a.date.localeCompare(b.date));
  const maxKcal = Math.max(...dates.map(d => dayTotals(state, d).kcal), 500);
  const latest = weights.at(-1), first = weights[0];
  return <><div className="page-heading"><div><h1>Progress</h1></div><div className="segmented compact">{[7, 30, 90, 365].map(n => <button className={period === n ? 'selected' : ''} key={n} onClick={() => setPeriod(n)}>{n === 365 ? '1 year' : `${n} days`}</button>)}</div></div><div className="stats-row"><div className="card"><p>Average intake</p><strong>{logged.length ? fmt(totalKcal / logged.length) : '—'}<small> kcal</small></strong><span>Across {logged.length} logged days</span></div><div className="card"><p>Average steps</p><strong>{active.length ? fmt(active.reduce((n, a) => n + (a?.steps ?? 0), 0) / active.length) : '—'}</strong><span>Across {active.length} recorded days</span></div><div className="card"><p>Weight change</p><strong>{weights.length > 1 ? `${latest!.kg > first.kg ? '+' : ''}${fmt(latest!.kg - first.kg, 1)}` : '—'}<small> kg</small></strong><span>{weights.length > 1 ? `${dateLabel(first.date)} – ${dateLabel(latest!.date)}` : 'Add two weigh-ins to see a trend'}</span></div></div>
    <section className="card"><SectionHeading title="Calories over time" aside={<span className="tag">{fmt(totalKcal)} kcal logged</span>} /><div className="long-chart" role="img" aria-label={`Calorie intake across ${period} days`}>
      {dates.map(d => <div className="history-bar" key={d} title={`${dateLabel(d)}: ${fmt(dayTotals(state, d).kcal)} kcal`}><div style={{ height: `${Math.max(dayTotals(state, d).kcal / maxKcal * 100, 1)}%` }} className={state.entries.some(e => e.date === d) ? 'has-data' : ''} /></div>)}
    </div><div className="chart-endpoints"><span>{dateLabel(dates[0])}</span><span>{dateLabel(date)}</span></div><p className="chart-caption">Averages exclude unlogged days.</p></section>
    <section className="card weight-history"><SectionHeading title="Weight history" aside={<button className="button secondary small-button" onClick={logWeight}><Plus size={16} />Log weight</button>} />{weights.length ? <><WeightChart weights={weights} /> <div className="weight-list">{weights.slice().reverse().map(w => <div key={w.date}><span>{dateLabel(w.date, { day: 'numeric', month: 'short', year: 'numeric' })}</span><strong>{fmt(w.kg, 1)} kg</strong><button className="icon-button" aria-label={`Delete weight for ${w.date}`} onClick={() => deleteWeight(w.date)}><Trash2 size={15} /></button></div>)}</div></> : <Empty title="No weigh-ins yet" detail="Log your weight to see a trend." />}</section>
    <section className="card"><SectionHeading title="Day-by-day detail" aside={<span className="tag">Last {period} days</span>} /><div className="table-scroll"><table><thead><tr><th>Date</th><th>Calories</th><th>Protein</th><th>Carbs</th><th>Fat</th><th>Steps</th><th>Active kcal*</th></tr></thead><tbody>{dates.slice().reverse().map(d => { const hasFood = state.entries.some(e => e.date === d), t = dayTotals(state, d), a = dayActivity(state, d); return <tr key={d}><td>{dateLabel(d, { day: 'numeric', month: 'short', year: 'numeric' })}</td><td>{hasFood ? fmt(t.kcal) : '—'}</td><td>{hasFood ? `${fmt(t.protein, 1)} g` : '—'}</td><td>{hasFood ? `${fmt(t.carbs, 1)} g` : '—'}</td><td>{hasFood ? `${fmt(t.fat, 1)} g` : '—'}</td><td>{a?.steps != null ? fmt(a.steps) : '—'}</td><td>{a?.activeKcal != null ? fmt(a.activeKcal) : '—'}</td></tr>; })}</tbody></table></div><p className="chart-caption">*Estimated activity energy. It does not include resting energy and is not subtracted from food intake.</p></section></>;
}
function WeightChart({ weights }: { weights: State['weights'] }) {
  if (weights.length < 2) return <p className="muted">Add a second weigh-in to see a trend.</p>;
  const min = Math.min(...weights.map(w => w.kg)) - 0.5, max = Math.max(...weights.map(w => w.kg)) + 0.5;
  const start = new Date(weights[0].date).getTime(), end = new Date(weights.at(-1)!.date).getTime();
  const points = weights.map(w => `${20 + (new Date(w.date).getTime() - start) / (end - start) * 760},${150 - (w.kg - min) / (max - min) * 120}`);
  return <div className="weight-chart"><span>{fmt(max, 1)} kg</span><svg viewBox="0 0 800 170" role="img" aria-label={`Weight from ${weights[0].kg} to ${weights.at(-1)!.kg} kg`}><path d="M20 50H780 M20 100H780 M20 150H780" fill="none" stroke="#e6ebe5" strokeDasharray="4 6" /><polyline points={points.join(' ')} stroke="#376b51" fill="none" strokeWidth="3" strokeLinejoin="round" />{points.map((p, i) => <circle key={i} cx={p.split(',')[0]} cy={p.split(',')[1]} r="4" fill="#376b51"><title>{dateLabel(weights[i].date)}: {weights[i].kg} kg</title></circle>)}</svg><span>{fmt(min, 1)} kg</span></div>;
}
