import { useState } from 'react';
import { ChefHat, Pencil, Plus, Search, Utensils } from 'lucide-react';
import { fmt, recipeTotals, type Food, type Recipe, type State } from './model';
import { Empty, MacroStrip } from './ui';

export function FoodLibrary({ state, add, edit, log }: { state: State; add: () => void; edit: (f: Food) => void; log: (f: Food) => void }) {
  const [query, setQuery] = useState(''), [category, setCategory] = useState('All foods');
  const foods = state.foods.filter(f => `${f.name} ${f.preparation}`.toLowerCase().includes(query.toLowerCase()) && (category === 'All foods' || category === 'My foods' && f.custom || f.group === category));
  return <><div className="page-heading"><div><p className="eyebrow">GOOD FOOD, LESS GUESSWORK</p><h1>Your food library.</h1><p>Choose your food. Weigh your portion. We’ll do the maths.</p></div><button className="button primary" onClick={add}><Plus size={18} />New food</button></div><div className="library-tools"><div className="search-box"><Search size={18} /><input aria-label="Search food library" placeholder="Search chicken, rice, beans…" value={query} onChange={e => setQuery(e.target.value)} /></div><select aria-label="Food category" value={category} onChange={e => setCategory(e.target.value)}>{['All foods', 'My foods', 'Protein', 'Grains', 'Vegetables', 'Fruit', 'Dairy', 'Fats', 'Other'].map(c => <option key={c}>{c}</option>)}</select></div><p className="library-caption">{foods.length} foods · nutrition per 100 g · match raw or cooked to how you weigh</p><div className="food-grid">{foods.map(f => <article className="card food-card" key={f.id}><div className="food-card-top"><span className={`food-category ${f.group.toLowerCase()}`}><Utensils size={20} /></span><span className="tag">{f.preparation}</span></div><h3>{f.name}</h3><p>{f.group}{f.custom ? ' · Your food' : ' · USDA reference'}</p><div className="food-calories"><strong>{fmt(f.per100.kcal)}</strong><span> kcal / 100 g</span></div><MacroStrip macros={f.per100} /><div className="food-card-actions">{f.custom ? <button className="text-button" onClick={() => edit(f)}><Pencil size={14} />Edit values</button> : <a href={f.sourceUrl} target="_blank" rel="noreferrer" className="source-link">USDA source ↗</a>}<button className="round-add" aria-label={`Log ${f.name} ${f.preparation}`} onClick={() => log(f)}><Plus size={19} /></button></div></article>)}</div>{!foods.length && <Empty title="Make it your own." detail="No foods match this search. You can add one using its nutrition label." action={<button className="button primary" onClick={add}>Create a food</button>} />}<p className="page-note">Reference foods: USDA FoodData Central, SR Legacy (April 2018). Products and cooking methods vary. Use your package’s values when available.</p></>;
}
export function Recipes({ state, add, edit, log }: { state: State; add: () => void; edit: (r: Recipe) => void; log: (r: Recipe) => void }) {
  return <><div className="page-heading"><div><p className="eyebrow">YOUR EVERYDAY FAVOURITES</p><h1>Cook once. Log simply.</h1><p>Turn your ingredients into meals you can come back to.</p></div><button className="button primary" onClick={add}><Plus size={18} />New recipe</button></div>{state.recipes.length ? <div className="recipe-grid">{state.recipes.map(r => { const totals = recipeTotals(r); return <article key={r.id} className="card recipe-card"><div className="recipe-art"><ChefHat size={50} strokeWidth={1.2} /><span>{r.ingredients.length} ingredients</span></div><div className="recipe-content"><h2>{r.name}</h2><p>{fmt(r.servings, 1)} servings · {fmt(r.yieldGrams)} g finished weight</p><strong className="recipe-kcal">{fmt(totals.kcal / r.servings)}<small> kcal / serving</small></strong><p className="muted">{fmt(totals.kcal)} kcal in the whole recipe</p><div className="recipe-actions"><button className="button secondary" onClick={() => edit(r)}><Pencil size={15} />Edit</button><button className="button primary" onClick={() => log(r)}><Plus size={16} />Log a portion</button></div></div></article>; })}</div> : <section className="card"><Empty title="Your next meal starts here." detail="Add chicken, rice, vegetables and anything else you cook with. Save the whole recipe, then log your portion in grams or servings." action={<button className="button primary" onClick={add}><Plus size={17} />Create your first recipe</button>} /></section>}<div className="recipe-tip"><ChefHat size={28} strokeWidth={1.5} /><div><h3>A tip for batch cooking</h3><p>Add the ingredients using the weights you measured. After cooking, weigh the whole finished dish. Steady uses that final weight to calculate each portion, even when cooking changes the water content.</p></div></div></>;
}
