import { useEffect, useState, type FormEvent } from 'react';
import { Cloud, Download, HardDrive, RefreshCw, ShieldCheck, Upload, LogOut, Smartphone } from 'lucide-react';
import { profileSchema, type Profile, type State } from './model';
import { Field, SectionHeading, formValues, optionalNumeric } from './ui';
import { cloud } from './cloud';
import { readMetadata, writeMetadata } from './storage';
import { saveLocalConnection, type LocalConnection } from './local-sync';
import ReminderSettings from './ReminderSettings';
import AppearanceSettings from './AppearanceSettings';
import type { AppearancePreference } from './appearance';

export type SyncMode = 'off' | 'cloud' | 'local';
export default function Settings({ appearance, state, saveProfile, download, restore, clear, sync, syncBusy, mode, setMode, status }: { appearance: { preference: AppearancePreference; set: (value: AppearancePreference) => void }; state: State; saveProfile: (p: Profile) => Promise<void>; download: () => void; restore: (f: File) => void; clear: () => void; sync: () => void; syncBusy: boolean; mode: SyncMode; setMode: (mode: SyncMode) => void; status: string }) {
  const [message, setMessage] = useState(''), [busy, setBusy] = useState(false), [email, setEmail] = useState('');
  const [local, setLocal] = useState<LocalConnection>({ url: 'http://localhost:4173', key: '' });
  useEffect(() => {
    void readMetadata<LocalConnection>('localConnection').then(v => v && setLocal(v));
    if (!cloud) return;
    void cloud.auth.getSession().then(({ data }) => setEmail(data.session?.user.email ?? ''));
    const { data } = cloud.auth.onAuthStateChange((_, session) => setEmail(session?.user.email ?? ''));
    return () => data.subscription.unsubscribe();
  }, []);
  async function save(e: FormEvent<HTMLFormElement>) {
    const d = formValues(e); setBusy(true); setMessage('');
    try { const profile = profileSchema.parse({ name: d.get('name'), age: optionalNumeric(d, 'age'), height: optionalNumeric(d, 'height'), startingWeight: optionalNumeric(d, 'startingWeight'), goalWeight: optionalNumeric(d, 'goalWeight'), calorieGoal: optionalNumeric(d, 'calorieGoal'), stepGoal: optionalNumeric(d, 'stepGoal') }); await saveProfile(profile); setMessage('Your profile is saved.'); } catch { setMessage('Check your profile values. Goals are optional and can be left blank.'); } finally { setBusy(false); }
  }
  async function signIn(e: FormEvent<HTMLFormElement>) {
    const d = formValues(e); if (!cloud) return; setBusy(true); setMessage('');
    try { const { error } = await cloud.auth.signInWithPassword({ email: String(d.get('email')), password: String(d.get('password')) }); if (error) throw error; setMode('cloud'); setMessage('Signed in. Your diary will sync automatically while the app is open.'); } catch (e) { setMessage(e instanceof Error ? e.message : 'Could not sign in.'); } finally { setBusy(false); }
  }
  async function connectLocal(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); setBusy(true); setMessage('');
    try { await saveLocalConnection(local); setMode('local'); setMessage('Local server connected. Sync is ready.'); } catch (e) { setMessage(e instanceof Error ? e.message : 'Could not reach the local server.'); } finally { setBusy(false); }
  }
  return <><div className="page-heading"><div><p className="eyebrow">MAKE STEADY YOURS</p><h1>A little setup.</h1><p>Your profile, your goals, your data.</p></div></div>{message && <div className="settings-message" role="status">{message}</div>}
    <AppearanceSettings {...appearance} /><div className="settings-columns"><section className="card"><SectionHeading title="Your profile" /><form key={JSON.stringify(state.profile)} onSubmit={save}><Field label="First name"><input name="name" maxLength={80} defaultValue={state.profile.name} autoComplete="given-name" placeholder="Your name" /></Field><div className="form-grid"><Field label="Age"><input name="age" type="number" min="18" max="120" step="1" defaultValue={state.profile.age ?? ''} /></Field><Field label="Height (cm)"><input name="height" type="number" min="80" max="250" step="any" defaultValue={state.profile.height ?? ''} /></Field><Field label="Starting weight (kg)"><input name="startingWeight" type="number" min="25" max="500" step="any" defaultValue={state.profile.startingWeight ?? ''} /></Field><Field label="Goal weight (kg) · optional"><input name="goalWeight" type="number" min="25" max="500" step="any" defaultValue={state.profile.goalWeight ?? ''} /></Field></div><h3 className="form-section">Daily goals</h3><p className="muted">Set a target you’ve chosen, or leave it blank and start by tracking. Activity calories won’t automatically increase your food target.</p><div className="form-grid"><Field label="Food target (kcal)"><input name="calorieGoal" type="number" min="1200" max="6000" step="1" placeholder="Not set" defaultValue={state.profile.calorieGoal ?? ''} /></Field><Field label="Step target"><input name="stepGoal" type="number" min="100" max="100000" step="1" placeholder="Not set" defaultValue={state.profile.stepGoal ?? ''} /></Field></div><button className="button primary" disabled={busy}>Save profile</button></form></section>
      <div><section className="card"><SectionHeading title="Your devices, together" aside={<Cloud size={20} />} /><p className="muted">Food and activity save on this device first. Choose how to share them with your other devices.</p><div className="segmented">{(['off', 'cloud', 'local'] as const).map(m => <button key={m} className={mode === m ? 'selected' : ''} onClick={() => setMode(m)}>{m === 'off' ? 'This device' : m === 'cloud' ? 'Hosted sync' : 'Local sync'}</button>)}</div>
        {mode === 'off' && <div className="connection-explainer"><HardDrive size={26} /><h3>Everything stays here.</h3><p>No sign-in needed. Export a backup to keep a second copy or transfer your diary.</p></div>}
        {mode === 'cloud' && (!cloud ? <div className="callout"><strong>One-time hosted setup needed</strong><p>Deploy the website on Vercel and connect a free Supabase project. The included deployment guide walks through the setup. After that, sign in here on your phone and desktop.</p></div> : email ? <div className="signed-in"><p>Signed in as <strong>{email}</strong></p><button className="button secondary small-button" onClick={async () => { await cloud?.auth.signOut(); setMode('off'); setMessage('Signed out. Local records remain on this device.'); }}><LogOut size={15} />Sign out</button></div> : <form onSubmit={signIn}><Field label="Email address"><input name="email" type="email" autoComplete="username" required /></Field><Field label="Password"><input name="password" type="password" autoComplete="current-password" required /></Field><button className="button primary" disabled={busy}>Sign in</button><p className="muted">Use the personal account created during Supabase setup.</p></form>)}
        {mode === 'local' && <form onSubmit={connectLocal}><p className="muted">Start the local server on your computer, then enter its address and pairing key. Each device uses the same key.</p><Field label="Local server URL"><input type="url" required value={local.url} onChange={e => setLocal({ ...local, url: e.target.value })} autoCapitalize="none" spellCheck={false} /></Field><Field label="Pairing key"><input type="password" required value={local.key} onChange={e => setLocal({ ...local, key: e.target.value })} autoComplete="off" /></Field><button className="button secondary" disabled={busy}>Connect local server</button><p className="muted">Localhost works on your computer or over Android USB forwarding. Home Wi-Fi uses a trusted HTTPS address; see the deployment guide.</p></form>}
        {mode !== 'off' && <div className="sync-controls"><button className="button primary" disabled={syncBusy || mode === 'cloud' && (!cloud || !email)} onClick={sync}><RefreshCw size={16} className={syncBusy ? 'spin' : ''} />{syncBusy ? 'Syncing…' : 'Sync now'}</button><p aria-live="polite">{status || 'Sync runs while this app is open and connected.'}</p></div>}
      </section><ReminderSettings /><section className="card backup-card"><SectionHeading title="Keep a copy" aside={<ShieldCheck size={20} />} /><p className="muted">A backup contains your food library, recipes, diary, activity and profile. Keep it somewhere private.</p><div className="backup-buttons"><button className="button secondary" onClick={download}><Download size={16} />Export backup</button><label className="button secondary file-button"><Upload size={16} />Restore backup<input type="file" accept=".json,application/json" onChange={e => { const file = e.target.files?.[0]; if (file) restore(file); e.target.value = ''; }} /></label></div><p className="muted">Restore replaces this device’s diary after you review the backup.</p><button className="text-button danger" onClick={clear}>Clear this device’s data</button></section><section className="privacy-note"><Smartphone size={20} /><p>No ads or analytics. Hosted sync sends your diary to your own Supabase project. <a href="/privacypolicy.html" target="_blank" rel="noreferrer">Privacy details ↗</a></p></section></div></div></>;
}
